const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{for(const width of [1440,393]){
const p=await b.newPage({viewport:{width,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/firebase/config.js',r=>r.fulfill({contentType:'text/javascript',body:"window.RoyFirebaseConfig={enabled:true,testOnly:true,authProvider:'google',firebase:{apiKey:'fake-test',authDomain:'fake-test.firebaseapp.com',projectId:'demo-roy-local',appId:'fake-test'}};"}));
await p.route('**/vendor/firebase-sdk.js',r=>r.fulfill({contentType:'text/javascript',body:`
const row=i=>({id:'fake-'+i,business_name:'架空'+i,classification:'Owned Presence',sent:false,status:'NOT_READY',readiness:'NOT_READY',preview_url:'https://example.invalid',confirmed_gates:[],missing_gates:[{code:'visual_qa',label:'QA確認'},{code:'initial_send_go',label:'営業GO'}],last_checked_at:'2026-10-08T10:00:00Z',email:{body:'変更禁止の架空本文'},contact:{email:'fake@example.invalid'}});
const values={'admins/fake-owner':{enabled:true},'control/source':{mode:'firestore'},'privatePipeline/current':{revision:1,sourceHash:'556ddf286d0d0a8b98e515870ce212f10318f3aba7fc007356df1d54413e2479',payload:{schema_version:1,cases:Array.from({length:8},(_,i)=>row(i)),summary:{operating_revenue_usd_last_recorded:0,ready_for_human_go:0,sent_cases_in_this_view:0}}}};const listeners={};
export const initializeApp=()=>({}),getAuth=()=>({currentUser:{uid:'fake-owner'}}),initializeFirestore=()=>({}),memoryLocalCache=()=>({}),inMemoryPersistence={},setPersistence=async()=>{},doc=(db,p)=>p,serverTimestamp=()=>null;
export function onIdTokenChanged(auth,fn){window.testAuth=fn;queueMicrotask(()=>fn({uid:'fake-owner'}));return()=>{};}
export function onSnapshot(path,opts,fn){listeners[path]=fn;queueMicrotask(()=>fn({metadata:{fromCache:false,hasPendingWrites:false},exists:()=>!!values[path],data:()=>values[path]}));return()=>{delete listeners[path];};}
export async function runTransaction(db,fn){await fn({get:async path=>({exists:()=>!!values[path],data:()=>values[path]}),set:(path,value)=>{values[path]=value;}});window.testSaved=values['privatePipeline/current'];for(const [path,fn] of Object.entries(listeners))fn({metadata:{fromCache:false,hasPendingWrites:false},exists:()=>!!values[path],data:()=>values[path]});}
export class GoogleAuthProvider{};export const signInWithPopup=async()=>{},signOut=async()=>window.testAuth(null);
`}));
await p.goto(process.env.DASHBOARD_URL||'http://127.0.0.1:8768');await p.locator('[data-view="settings"]').click();await p.waitForSelector('#firebase-editor:not([hidden])');
assert.equal(await p.locator('#firebase-gates input[data-code="initial_send_go"]').isDisabled(),true);
await p.locator('#firebase-gates input[data-code="visual_qa"]').check();await p.locator('#firebase-state').selectOption('READY_FOR_HUMAN_GO');await p.locator('#firebase-next').fill('次の確認');await p.locator('#firebase-save').click();
await p.waitForFunction(()=>window.testSaved?.revision===2);const saved=await p.evaluate(()=>window.testSaved);assert.equal(saved.payload.cases[0].status,'READY_FOR_HUMAN_GO');assert.equal(saved.payload.cases[0].email.body,'変更禁止の架空本文');assert.equal(saved.payload.summary.ready_for_human_go,1);assert.ok((await p.locator('#firebase-test-summary').innerText()).includes('実績ではありません'));assert.equal(await p.locator('#sales-metrics .sales-metric').filter({has:p.locator('span', {hasText:'送信済み'})}).locator('strong').textContent(),'1件');assert.ok((await p.locator('#priority-source').textContent()).includes('架空')); assert.ok(!(await p.locator('#sales-source').innerText()).includes('Firestore'));
assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await p.locator('#firebase-logout').click();assert.equal(await p.locator('#firebase-editor').isVisible(),false);assert.equal(await p.locator('.case-card').count(),0);assert.deepEqual(errors,[]);console.log('PASS mocked Firebase UI '+width+'px: gate/status save, preserved body, live projection, signout clear');await p.close();
}}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
